### ISSUE TITLE
在ggcoverage中的facet.key、facet.order、facet.color这三个参数的具体含义和可选内容？

### ISSUE THREAD

**Issue by wsweishang** [showteeth/ggcoverage#1]
请问1）在ggcoverage中，facet.key、facet.order、facet.color这三个参数的具体含义代表什么？分别都有哪些可选内容？
2）为何我设置facet.color = c("red", "green", "yellow", "blue")给示例文件，会提示报错：Error in CeilingNumber(max(.x)) : object 'x.ceiling' not found

![1665998673427_DC4273DC-CD49-439d-97CC-18ECAF81042E](https://user-images.githubusercontent.com/35129244/196141339-9d9fd4aa-cee7-489a-83f0-b09e3771206d.png)

**Comment by showteeth** [comment]
1. facet相关的参数是用来控制不同track以及对应的右侧标签信息的，`facet.key`是sample.meta里面的Type列，`facet.order`会决定不同track的先后顺序，`facet.color`是右侧标签的背景颜色
2. 没有设置`facet.color`的话会有这个报错吗？理论上应该不会因为这个参数报这个错

如果可以的话，你可以把你的数据发我邮箱吗？我来测试一下

**Comment by wsweishang** [comment]
1）facet.color用的就是manual里的示例数据，会提示如图所示的报错，完整代码如下；2）这个参数应该设置为一组颜色的向量吗？facet.color = c("red", "green", "yellow", "blue")。

> library("rtracklayer")
> library("ggcoverage")
> ## RNA
> # load metadata
> meta.file <- system.file("extdata", "RNA-seq", "meta_info.csv", package = "ggcoverage")
> sample.meta = read.csv(meta.file)
> sample.meta
       SampleName    Type Group
1 ERR127302_chr14 KO_rep1    KO
2 ERR127303_chr14 KO_rep2    KO
3 ERR127306_chr14 WT_rep1    WT
4 ERR127307_chr14 WT_rep2    WT
> # track folder
> track.folder = system.file("extdata", "RNA-seq", package = "ggcoverage")
> # load bigwig file
> track.df = LoadTrackFile(track.folder = track.folder, format = "bw", meta.info = sample.meta)
> head(track.df)
  seqnames    start      end score    Type Group
1    chr14 21572751 21630650     0 KO_rep1    KO
2    chr14 21630651 21630700     1 KO_rep1    KO
3    chr14 21630701 21630800     4 KO_rep1    KO
4    chr14 21630801 21657350     0 KO_rep1    KO
5    chr14 21657351 21657450     1 KO_rep1    KO
6    chr14 21657451 21663550     0 KO_rep1    KO
> # create mark region
> mark.region=data.frame(start = c(21678900, 21732001, 21737590), end = c(21679900, 21732400, 21737650), label = c("M1", "M2", "M3"))
> # check data
> mark.region
     start      end label
1 21678900 21679900    M1
2 21732001 21732400    M2
3 21737590 21737650    M3
> gtf.file = system.file("extdata", "used_hg19.gtf", package = "ggcoverage")
> gtf.gr = rtracklayer::import.gff(con = gtf.file, format = 'gtf')
> # basic plot
> ggcoverage(data = track.df, color = c("red", "green", "yellow", "blue"), mark.region = mark.region, range.position = "out", 
+            facet.key = "Type", facet.order = NULL, facet.color = c("red", "green", "yellow", "blue"))
Error in CeilingNumber(max(.x)) : object 'x.ceiling' not found
>

**Comment by showteeth** [comment]
I updated `ggcoverage` to fix this issue, you can have a try.

Please let me know if you have any problems!
