### ISSUE TITLE
Where to start for ATAC-seq data?

### ISSUE THREAD

**Issue by priscilla-glenn** [showteeth/ggcoverage#10]
Hi, I have some scATAC-seq data and I would like to graph the coverage across the different chromosomes, especially the X and the Y. I notice that you have a section called DNA-seq which has the following:

```
# track file
track.file = [system.file](https://rdrr.io/r/base/system.file.html)("extdata", "DNA-seq", "CNV_example.txt", package = "ggcoverage")
# load txt file
track.df = [LoadTrackFile](https://showteeth.github.io/ggcoverage/reference/LoadTrackFile.html)(track.file = track.file, format = "txt", region = "chr4:61750000-62,700,000",
                         meta.info = cnv.meta.info)
```

What data is in the CNV_example.txt? Do I need to calculate coverage before using ggcoverage? If so, what software would you recommend for ease of transferring it to ggcoverage? In the next section, I see that the region is limited to a section on chr4. If I want to visualize the entire chromosome, would like change to chr4:1-full_length? I have little experience with the system.file usage so I apologize for any basic questions. 

Thank you in advance for your help!

**Comment by showteeth** [comment]
Hi,

The example gives the usage for different kinds of files, `ggcoverage` is **based on track files**, which can be in `bam`, `bigwig`, `txt`, et al. 

If you need an example usage,  ATAC-seq and ChIP-seq are similar, so you can consider the usage of [ChIP-seq](https://showteeth.github.io/ggcoverage/#chip-seq-data).

You can use `LoadTrackFile` directly to load `bam`, `bigwig`, `txt`, et al. 

For visualizing the entire chromosome, you can change to **chr4:1-[the length of the chromosome]**.

Hope it helps,

YB
