### ISSUE TITLE
Getting installation error

### ISSUE THREAD

**Issue by ayooluwaB** [showteeth/ggcoverage#13]
When I try to install the package in R in a Linux environment, all installation methods give a non-zero exit status. 

I have updated both R and R studio to R.4.3.1
See Error messages below:

/usr/bin/ld: cannot find -llapack: No such file or directory
/usr/bin/ld: cannot find -lblas: No such file or directory
collect2: error: ld returned 1 exit status
make: *** [/usr/share/R/share/make/shlib.mk:10: RcppArmadillo.so] Error 1
ERROR: compilation failed for package ‘RcppArmadillo’

Warning in install.packages :
  installation of package ‘RcppArmadillo’ had non-zero exit status
ERROR: dependency ‘RcppArmadillo’ is not available for package ‘ade4’

Warning in install.packages :
  installation of package ‘ade4’ had non-zero exit status
ERROR: dependency ‘ade4’ is not available for package ‘seqinr’
’
Warning in install.packages :
  installation of package ‘seqinr’ had non-zero exit status
ERROR: dependencies ‘GenomicRanges’, ‘ggbio’, ‘IRanges’, ‘Rsamtools’, ‘rtracklayer’, ‘GenomeInfoDb’, ‘S4Vectors’, ‘Biostrings’, ‘BSgenome’, ‘GenomicAlignments’, ‘seqinr’ are not available for package ‘ggcoverage’
* removing ‘/home/abolaji/R/x86_64-pc-linux-gnu-library/4.3/ggcoverage’
Warning in install.packages :
  installation of package ‘ggcoverage’ had non-zero exit status

**Comment by showteeth** [comment]
Hi, 
It seems that you should install `liblapack-dev` and `libopenblas-dev`, [here](https://stackoverflow.com/questions/27033243/usr-bin-ld-cannot-find-llapack) is the detailed information.

YB
