### ISSUE TITLE
Error in CeilingNumber(max(.x)) : object 'x.ceiling' not found

### ISSUE THREAD

**Issue by ofircohn** [showteeth/ggcoverage#14]
Hi! The package looks great!

I found this error in the current version (ggcoverage_1.2.0).
https://github.com/showteeth/ggcoverage/issues/1.

track.df = LoadTrackFile(track.file =/path/to/'Cells.bedGraph', format = "bedgraph",meta.info = NULL,region = "chr2:102415689-102455565")
Sample without metadata!
> head(track.df)
  seqnames     start       end score           Type          Group
1     chr2 102418385 102419013     0 Cells.bedGraph Cells.bedGraph
2     chr2 102422977 102423192     0 Cells.bedGraph Cells.bedGraph
3     chr2 102424446 102425154     0 Cells.bedGraph Cells.bedGraph
4     chr2 102425478 102425997     0 Cells.bedGraph Cells.bedGraph
5     chr2 102430644 102430927     0 Cells.bedGraph Cells.bedGraph
6     chr2 102435476 102436635     0 Cells.bedGraph Cells.bedGraph

ggcoverage(data = track.df, color = "grey",
                            mark.region = NULL, range.position = "out")

Error in CeilingNumber(max(.x)) : object 'x.ceiling' not found

Thank you!

**Comment by showteeth** [comment]
Hi, 
Can you please check the `score` column of `track.df`, are they all zero?

**Comment by ofircohn** [comment]
Yes. They are all zero. 
I'm trying to present cell-type specific peaks so I extracted them from signac (https://stuartlab.org/signac/reference/callpeaks).

**Comment by showteeth** [comment]
@m-jahn 

It's true that it's easy to fix, but I don't know why showing zero tracks.

Yes, welcome contributions!

This time I updated it, next time you can have a try! Thanks a lot!

YB
