### ISSUE TITLE
在ggcoverage中绘制基因结构的注释图的三个问题

### ISSUE THREAD

**Issue by wsweishang** [showteeth/ggcoverage#2]
**1）读取的gff文件需要包含哪些基因信息，才能正常绘制？**
原本用烟草参考基因组注释文件画图时会报错：
```R
> basic.coverage + geom_gene(gtf.gr = gtf.gr)
Error in `dplyr::select()`:
! Can't subset columns that don't exist.
✖ Column `gene_type` doesn't exist.
Run `rlang::last_error()` to see where the error occurred.
> 
```
对比示例gtf文件，发现缺少一些基因注释信息，手动补充了一下，可以画出来了，**但是读取的gff文件需要包含哪些基因信息，才能正常绘制？**

![3D6B2F83-DD18-4809-A3D5-8562AE57C743](https://user-images.githubusercontent.com/35129244/196841295-12fa03df-3e9d-4e39-a47e-51f56334bd42.png)
![90573A0F-BA15-41f2-8981-04C121FFF08F](https://user-images.githubusercontent.com/35129244/196841824-49a821c5-1270-48b0-a943-c18b4b7a2733.png)

**2）目标基因有7个外显子，为何只显示六个？**
**目标基因包含有7个外显子，为何只显示六个？图中的各形状分别代表哪些基因信息？此外是否有图例参考？**
![520A217C-3992-4006-9947-CD4D0A0D33F6](https://user-images.githubusercontent.com/35129244/196842130-20f72100-40c3-4718-8508-ce6894a213d9.png)

**3）目标基因所在的基因组区间也不对**
**目标基因位于421068-432552，为何图上从420000之前就开始？**
![4B18FB67-B159-4029-B019-38651CE0CB37](https://user-images.githubusercontent.com/35129244/196842155-99aa06b9-13bd-4360-837b-c08c12be4c4f.png)

4）可否提供您的邮箱以便发送代码和输入文件测试？

**Comment by showteeth** [comment]
Thanks for your feedback! 

[E-mail](songyb0519@gmail.com)
