### ISSUE TITLE
Column `seqnames` doesn't exist when adding geom_gene()

### ISSUE THREAD

**Issue by huipan1973** [showteeth/ggcoverage#24]
I ran the following code:

plt <- ggcoverage(data = data, plot.type = "joint", facet.key = "Type", group.key = "Group", joint.avg = TRUE, range.position = "out")
plt <- plt + geom_gene(gtf.gr = gtf.gr)

But I got the error message:
Error in `track.data[1, "seqnames"]`:
! Can't subset columns that don't exist.
✖ Column `seqnames` doesn't exist.

Here is the details of traceback()

23: stop(fallback)
22: signal_abort(cnd)
21: cnd_signal(cnd)
20: (function (cnd) 
    {
        cnd$subscript_arg <- j_arg
        cnd$subscript_elt <- "column"
        if (isTRUE(assign) && !isTRUE(cnd$subscript_action %in% c("negate"))) {
            cnd$subscript_action <- "assign"
        }
        cnd_signal(cnd)
    })(structure(list(message = "", trace = structure(list(call = list(
        `+.gg`(plt, geom_gene(gtf.gr = gtf.gr)), e1 %+% e2, add_ggplot(e1, 
            e2, e2name), ggplot_add(object, p, objectname), ggplot_add.gene(object, 
            p, objectname), track.data[1, "seqnames"], `[.grouped_df`(track.data, 
            1, "seqnames"), NextMethod(), `[.tbl_df`(track.data, 
            1, "seqnames"), vectbl_as_col_location(j, length(x), 
            names(x), j_arg = j_arg, assign = FALSE), subclass_col_index_errors(vec_as_location(j, 
            n, names, missing = "error", call = call), j_arg = j_arg, 
            assign = assign), withCallingHandlers(expr, vctrs_error_subscript = function(cnd) {
            cnd$subscript_arg <- j_arg
            cnd$subscript_elt <- "column"
            if (isTRUE(assign) && !isTRUE(cnd$subscript_action %in% 
     ...
19: signalCondition(cnd)
18: signal_abort(cnd, .file)
17: abort(class = c(class, "vctrs_error_subscript"), i = i, ..., 
        call = call)
16: stop_subscript(class = "vctrs_error_subscript_oob", i = i, subscript_type = subscript_type, 
        ..., call = call)
15: stop_subscript_oob(i = i, subscript_type = subscript_type, names = names, 
        subscript_action = subscript_action, subscript_arg = subscript_arg, 
        call = call)
14: (function () 
    stop_subscript_oob(i = i, subscript_type = subscript_type, names = names, 
        subscript_action = subscript_action, subscript_arg = subscript_arg, 
        call = call))()
13: vec_as_location(j, n, names, missing = "error", call = call)
12: withCallingHandlers(expr, vctrs_error_subscript = function(cnd) {
        cnd$subscript_arg <- j_arg
        cnd$subscript_elt <- "column"
        if (isTRUE(assign) && !isTRUE(cnd$subscript_action %in% c("negate"))) {
            cnd$subscript_action <- "assign"
        }
        cnd_signal(cnd)
    })
11: subclass_col_index_errors(vec_as_location(j, n, names, missing = "error", 
        call = call), j_arg = j_arg, assign = assign)
10: vectbl_as_col_location(j, length(x), names(x), j_arg = j_arg, 
        assign = FALSE)
9: `[.tbl_df`(track.data, 1, "seqnames")
8: NextMethod()
7: `[.grouped_df`(track.data, 1, "seqnames")
6: track.data[1, "seqnames"]
5: ggplot_add.gene(object, p, objectname)
4: ggplot_add(object, p, objectname)
3: add_ggplot(e1, e2, e2name)
2: e1 %+% e2
1: `+.gg`(plt, geom_gene(gtf.gr = gtf.gr))

**Comment by m-jahn** [comment]
Hi @huipan1973 
Can you add a fully reproducible example? What is `data` in your case, is it from the provided examples?

**Comment by huipan1973** [comment]
Nevermind, I figured it out. It was because that the plot$layers[[1]]$data used by geom_gene() did not have the seqnames and end columns. I manually fixed it by adding the following code:

plt$layers[[1]]$data %<>% as.data.frame() %>% mutate(seqnames = "MT", end = start)
