### ISSUE TITLE
incorrect annotations

### ISSUE THREAD

**Issue by herber4** [showteeth/ggcoverage#3]
<img width="434" alt="Screen Shot 2022-11-14 at 7 19 01 AM" src="https://user-images.githubusercontent.com/55756028/201658328-46b64913-93d7-425f-9849-0c3b96bc8984.png">

not able to add gene annotations - I assume this is due to using a different annotation from what's in the tutorial. If this is the case, can you please provide the correct annotations, or make a statement regarding which annotations to use in the tutorial.

**Comment by showteeth** [comment]
Hi,     
I have uploaded a new version, in which I marked the information that the gtf file should contain.
>To add **gene annotation**, the gtf file should contain **gene_type** and **gene_name** attributes in **column 9**; to add **transcript annotation**, the gtf file should contain **transcript_name** attribute in **column 9**.

**Comment by stiv1n** [comment]
I have the same problem. Try to use your script with annotation for hg38 from ensembl.

One problem is gene_type is gene_biotype 
another is different coloumns. 

yours:
##gff-version 2
##source-version rtracklayer 1.50.0
##date 2022-07-20
chr4	ENSEMBL	gene	61788337	61788402	.	+	.	gene_id "ENSG00000265829.1"; transcript_id "ENSG00000265829.1"; gene_type "miRNA"; gene_status "KNOWN"; gene_name "MIR548AG1"; transcript_type "miRNA"; transcript_status "KNOWN"; transcript_name "MIR548AG1"; level "3";

closest i can get with standard tools:

##gff-version 2
##source-version rtracklayer 1.54.0
##date 2022-11-25
4	mirbase	gene	112647874	112647941	.	-	.	gene_id "ENSG00000199169"; gene_version "1"; gene_name "MIR367"; gene_source "mirbase"; gene_type "miRNA";
4	mirbase	transcript	112647874	112647941	.	-	.	gene_id "ENSG00000199169"; gene_version "1"; gene_name "MIR367"; gene_source "mirbase"; gene_type "miRNA"; transcript_id "ENST00000362299"; transcript_version "1"; transcript_name "MIR367-201"; transcript_source "mirbase"; transcript_biotype "miRNA"; tag "basic"; transcript_support_level "NA"

**Comment by showteeth** [comment]
I am sorry, I can not follow you based on the information you provided.     
Would you mind providing:

- the version of `ggcoverage` you used
- the code you used
- the gtf file you used and the test data

**Comment by stiv1n** [comment]
Certainly 
I am sorry for my poor description. I was agitated. 
The GTF is the latest ensembl hg38
https://ftp.ensembl.org/pub/release-108/gtf/homo_sapiens/Homo_sapiens.GRCh38.108.gtf.gz

Here are trimmed coverage files:
[files.zip](https://github.com/showteeth/ggcoverage/files/10094329/files.zip)

ggcoverage 0.7.1

code:
gr_larp7 <- GRanges(seqnames = "4",  ranges = IRanges(start = 112631446, width =  32040))
sample_meta<- data.frame(c("file1", "file2", "file3", "file4", "file5"),
                         c("file1", "file2", "file3", "file4", "file5"),
                         c("WT", "KO", "NF", "WT", "KO"))
track.df = LoadTrackFile(track.folder = track_folder, format = "bw",
                         meta.info = sample_meta,bin.size = 5,norm.method = "None")
mark.region=data.frame(start=112647034,
                       end=112647834,
                       label="circLARP7")
gtf.gr.test = rtracklayer::import.gff(con = "test.gtf", format = 'gtf' , which=gr_larp7)

basic.coverage = ggcoverage(data = track.df, color = "auto", region = "4:112,646,248-112,648,830", 
                            mark.region=mark.region, show.mark.label = FALSE,extend=200)


basic.coverage #works fine

#neither works
basic.coverage + geom_gene(gtf.gr=gtf.gr.test)
basic.coverage + geom_transcript(gtf.gr=gtf.gr.test,label.vjust = 1.5)

**Comment by showteeth** [comment]
Sorry for the late response!     
To solve your problems: 

- update you `ggcoverage`:
```R
# install via Github
# install.package("remotes")   #In case you have not installed it.
remotes::install_github("showteeth/ggcoverage")
```

- The following codes work fine:
```R
library(ggcoverage)
library(ggplot2)
library(GenomicRanges)
sample_meta<- data.frame(SampleName = c("file1", "file2", "file3", "file4", "file5"),
                         Type = c("file1", "file2", "file3", "file4", "file5"),
                         Group = c("WT", "KO", "NF", "WT", "KO"))
track.df = LoadTrackFile(track.folder = './debug/ggcoverage_issue3',
                         format = "bw",
                         meta.info = sample_meta,bin.size = 5,norm.method = "None")
mark.region=data.frame(start=112647034,
                       end=112647834,
                       label="Focus")

gr_larp7 <- GRanges(seqnames = "4", ranges = IRanges(start = 112631446, width = 32040))
gtf.gr.test = rtracklayer::import.gff(con = "./debug/Homo_sapiens_hg38.gtf",
                                      format = 'gtf' , which=gr_larp7)

basic.coverage = ggcoverage(data = track.df, color = "auto", region = "4:112,646,248-112,648,830",
                            mark.region=mark.region, show.mark.label = FALSE, extend=200)

basic.coverage + geom_gene(gtf.gr=gtf.gr.test)
# you should specify gene.name
basic.coverage + geom_transcript(gtf.gr=gtf.gr.test,label.vjust = 1.5, gene.name = "LARP7")
```
![image](https://user-images.githubusercontent.com/43517166/204128861-1d320ec0-d170-41c0-96f1-bc03359fcfac.png)

![image](https://user-images.githubusercontent.com/43517166/204128875-366596bc-9813-443b-b267-876071f2cf78.png)

**Comment by stiv1n** [comment]
It was a rather fast response given that you needed to make to update the package. 
Thanks! Good luck!
