### ISSUE TITLE
any smooth parameter

### ISSUE THREAD

**Issue by ileump** [showteeth/ggcoverage#32]
hi, 
I'd like to ask if ggcoverage has parameters related to smooth?

**Comment by m-jahn** [comment]
Hi!
No sorry, there is no smoothing parameter to really smooth the coverage plots. However, since the input are regular data frames you can apply any type of smoothing to the data beforehand. See these two examples, using `rollapply` from the `zoo` package. The result is not super pretty with such sparse data but I think the message is clear.

```
library(ggcoverage)
library(ggplot2)
library(zoo)

# import track data
meta.file <- system.file("extdata", "RNA-seq", "meta_info.csv", package = "ggcoverage")
sample.meta <- utils::read.csv(meta.file)
track.folder <- system.file("extdata", "RNA-seq", package = "ggcoverage")

track.df <- LoadTrackFile(
  track.folder = track.folder,
  format = "bw",
  meta.info = sample.meta,
  region = "chr14:21,677,306-21,737,601"
)

# plot tracks without smoothing
ggplot() +
  geom_coverage(data = track.df, facet.key = "Type", group.key = "Group")
```

![image](https://github.com/showteeth/ggcoverage/assets/32667667/b09451bb-9265-4150-b9a0-c4a2e4fb83f5)

```
# plot tracks with smooting
track.df <- track.df %>%
  group_by(Type) %>%
  mutate(score = zoo::rollapply(score, width = 5, FUN = mean, fill = 0)) %>%
  as.data.frame()

ggplot() +
  geom_coverage(data = track.df, facet.key = "Type", group.key = "Group")
```

![image](https://github.com/showteeth/ggcoverage/assets/32667667/13bcc6ea-5c64-465a-be2e-d3e43df4f98f)

**Comment by ileump** [comment]
![image](https://github.com/showteeth/ggcoverage/assets/87130950/f548f633-b926-47da-9a6f-2478574ead1e)

![image](https://github.com/showteeth/ggcoverage/assets/87130950/1af9a0c8-abc8-41b2-8c85-470bbaf9b82a)
Thank you for your response. About the 'smooth' parameter, previously I visualized the .bw files using https://epigenomegateway.wustl.edu/browser/, as shown in the figure. I'm not sure if the 'smooth' parameter in that tool is consistent with the method you mentioned?

**Comment by m-jahn** [comment]
No this is for sure something different. My example was only to show that you can apply any function of choice to the peak/score data. It's an R-builtin data type, the data.frame, so you can scale or transform the data as you like before plotting. To find a smoothing function that works for you is up to you though.

**Comment by ileump** [comment]
Thank for your time.

**Comment by m-jahn** [comment]
Maybe `smooth.spline` is the function you are looking for to smooth your Y-data.
This example works with an equal-spaced coverage (10 nt window) from a random bam file.
Compare the upper non-smoothed with lower smoothed coverage.

```
library(ggcoverage)
library(tidyverse)

track.df <- LoadTrackFile(
  track.file = "~/Downloads/spn_filt.bam",
  format = "bam",
  norm.method = "None"
)

# add track with smoothed Y data
track.df <- bind_rows(
  track.df,
  track.df %>%
  mutate(
    score = smooth.spline(x = start, y = score, spar = 0.2)$y,
    Type = "spn_filt Smoothed"
  ) %>%
  as.data.frame()
)

ggplot() +
  geom_coverage(data = track.df, facet.key = "Type", group.key = "Group")
```

![image](https://github.com/showteeth/ggcoverage/assets/32667667/b052863d-6c23-401b-b676-e8e7c7701693)

Sorry for the quality, this is an artifact of plotting high density bars in low res.
