### ISSUE TITLE
Unable to install ggcoverage package on MacOS 14.4.1

### ISSUE THREAD

**Issue by sebel76** [showteeth/ggcoverage#34]
Hi,

I am looking to try your software. However, I am unable to install it on RStudio (RStudio-2024.04.1-748) or R (R-4.4.0-x86_64). I am working on MacOS 14.4.1.

> install.packages("ggcoverage")
Warning in install.packages :
  package ‘ggcoverage’ is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages

Please, can you provide assistance?

Best,
Sébastien

**Comment by m-jahn** [comment]
Hi @sebel76, this is difficult to reproduce for me. Your version of R seems to be up-to-date.
I can install the package on R 4.4.0 on linux, and the build for Mac OS seems to be fine too according to the automatic R CMD CHECK results.

You can try to install the latest version from my branch using

```
devtools::install_github("m-jahn/ggcoverage", ref = "dev")
```

Is there any more output from R? Usually it complains about missing dependencies etc.

**Comment by sebel76** [comment]
Hi Michael,

Thank you for your quick response. The installation works with your proposed method!

Best,
Sébastien
