### ISSUE TITLE
Suggestion: differential colors for different peaks based on score or other colunm in narrowPeak file

### ISSUE THREAD

**Issue by pedrodelosreyes** [showteeth/ggcoverage#35]
Hello!,

very useful package, thank you very much. I have used for visualize RNAseq data and currently I am plotting CUT&TAG data. I have load my peak file (narrowPeak file from MACS) and I would like to color the different peaks based on the score, q-value, signalvalue... Is that possible?

Thank you very much!!

Pedro.

**Comment by m-jahn** [comment]
Hi Pedro, can you provide a minimal reproducible example? Personally I have never used a narrowPeak file, so I'm not sure how the visualization looks like and what you want to style differently. Feel free to add an example picture indicating what you want to achieve.

**Comment by pedrodelosreyes** [comment]
Hi Michael, 

of course. BED files require at least 3 fields indicating the genomic location of the feature, but usually has 6 fields (chromosome, start, end, name, score and strand). The narrowPeak file is a BED 6+4 format, which means the first 6 columns of a standard BED file with 4 additional fields.
![image](https://github.com/showteeth/ggcoverage/assets/44755742/175a8424-1ffa-482a-a529-886a6d9c8586)

I would like to color independently the peaks based on the numeric values from one column (such as score, or p-value), using a gradient color. This is what I have: 
![AT5G60910_AGL8_groups](https://github.com/showteeth/ggcoverage/assets/44755742/8fb69007-6c12-4dbe-a88b-aebb872a9878)

And this is what I want to achieve, for example, with a grey color gradient: 
![example](https://github.com/showteeth/ggcoverage/assets/44755742/085d4ab7-9be4-457b-a07f-3bf6964ce1c5)

Furthermore, I take advantage of this issue to ask you if it is possible to add multiple peak tracks. This is my code:
basic_coverage <- ggcoverage(
    data = track.df,
    plot.type = "facet",
    facet.key = "Group",
    group.key = "Group",
    # mark.region = mark_region,
    range.position = "in",
    facet.y.scale = "fixed",
    color = my.colors,
    facet.color = my.colors
  )

  basic_coverage +
    geom_peak(bed.file = peaks, peak.size = 3) +
    # theme(legend.text = element_text(size=10)) +
    geom_gene(gtf.gr = gtf.atha,
              fill.color = c("gray32","gray70"),
              gene.size = 1,
              arrow.size = 1.5,
              plot.space = 0.2,
              plot.height = 0.2)

I tried to add another "geom_peak" line to include another track of peaks (for example, to plot peaks from different biological replicates instead of the consensus set of peaks), but it did not work. 

Thanks you very much! 

Best, 

Pedro.

**Comment by m-jahn** [comment]
Hi Pedro, thanks for getting back with all these details, that's great. I edited your answer regarding just to highlight the code section. I look into that.

**Comment by m-jahn** [comment]
Hi Pedro, you are correct, there is no builtin method to color-code the `geom_peak` output.
I tried to make some changes to this function that allows color-coding. You can check out the `dev` branch from my fork:
https://github.com/m-jahn/ggcoverage/tree/dev

The latest commit will allow you to plot with `geom_peak` as shown in the following example. It will accept any named column in the bedfile as input for color coding, whether it's numeric or categorical data.

```
library(tidyverse)
library(ggcoverage)

# load metadata
sample_meta <- data.frame(
  SampleName = c(
    "Chr18_MCF7_ER_1",
    "Chr18_MCF7_ER_2",
    "Chr18_MCF7_ER_3",
    "Chr18_MCF7_input"
  ),
  Type = c("MCF7_ER_1", "MCF7_ER_2", "MCF7_ER_3", "MCF7_input"),
  Group = c("IP", "IP", "IP", "Input")
)

# import coverage track
track_folder <- system.file("extdata", "ChIP-seq", package = "ggcoverage")
track_df <- LoadTrackFile(
  track.folder = track_folder,
  format = "bw",
  region = "chr18:76822285-76900000",
  meta.info = sample_meta
)

# create mock peak file
df_peaks <- data.frame(
  seqnames = c("chr18", "chr18", "chr18"),
  start = c(76822533, 76846900, 76880000),
  end = c(76836900, 76860000, 76887000),
  score = c(4, 6, 13)
)

# plot with default color
ggcoverage(data = track_df) +
  geom_peak(peak.df = df_peaks, peak.size = 3)

# plot with color by 'score' variable
ggcoverage(data = track_df) +
  geom_peak(peak.df = df_peaks, peak.size = 3, color.by = "score")

# plot with color by 'score' variable and custom color scale
ggcoverage(data = track_df) +
  geom_peak(peak.df = df_peaks, peak.size = 3, color.by = "score", peak.color = rainbow(5))
```

![image](https://github.com/showteeth/ggcoverage/assets/32667667/bc6cc4f6-633d-4229-b959-04f4d891ab11)

Let me know if this is what you want to have.

**Comment by pedrodelosreyes** [comment]
Hi Michael, 

thanks for that, it is really great. 

Just one question, in the example image that you have posted there are only 3 peaks and they are colored based on the score column.

Imagine that I have 1000 peaks and I only plot 3 in my region of interest:
 * Are only those 3 peaks taken into account to obtain the color code? I would like the 1000 peaks to be taken into account to obtain the color code (heatmap) and then color those 3 peaks. Thus, peaks in different plots will be comparable. 

Thanks again,

**Comment by m-jahn** [comment]
I see what you mean. No problemo, there are no extra parameters required. The fantastic thing about `ggplot` is  that you can always change/override existing theme elements with new commands. In this example below I set a new color scale with defined limits. You see that the chosen colors are not spanning the original range from the data but the one I defined with `limits`:

```
# create mock peak file
df_peaks <- data.frame(
  seqnames = c("chr18", "chr18", "chr18"),
  start = c(76822533, 76846900, 76880000),
  end = c(76836900, 76860000, 76887000),
  score = c(4, 9, 16)
)

# plot with color by 'score' variable
ggcoverage(data = track_df) +
  geom_peak(peak.df = df_peaks, peak.size = 3, color.by = "score") +
  scale_color_gradientn(colors = rainbow(10), limits = c(0, 30)) +
  theme(legend.position = "bottom")
```

![image](https://github.com/showteeth/ggcoverage/assets/32667667/d4156082-f702-4d6a-9dd3-4892cef8e2ed)

**Comment by pedrodelosreyes** [comment]
Hi Michael, 

yes, that is what I was looking for. Thank you very much. I will try it. 

Pedro
