### ISSUE TITLE
Old arrow appearance and acknowledgments

### ISSUE THREAD

**Issue by bvaldebenitom** [showteeth/ggcoverage#38]
Hi there,

in the past I used ggcoverage to generate some plots, in which the arrow appearance was different, as shown here:
![README-gene_coverage-1](https://github.com/user-attachments/assets/8c5f4c46-8ebf-49d6-af9e-ed913432366a)

it seems this was changed to:
![README-gene_coverage-1](https://github.com/user-attachments/assets/88bd1858-97c1-4a01-b1d2-69a40ece4106)

I tried installing the old version, but didn't seem to have reverted back. Is there any option to return to the old appearance, or a snippet of code that specifically changes the gene track appearance?

Additionally, I would like to give my sincerest thanks for developing this tool. I use ggplot2 for all my plots, and when this tool was published I was quite happy about it. It allowed me to make some nice representations for my paper (Figure 8, [recently published here](https://www.nature.com/articles/s41598-024-73744-7)).

Thanks,
Braulio.

**Comment by m-jahn** [comment]
Dear Braulio, thanks for your feedback. I think you have two options to get this arrow style that you prefer:

1. check out a version before the change of arrow style, commit [afc2b17](https://github.com/showteeth/ggcoverage/pull/31/commits/afc2b17af005711d333232a01add345b90dc22d9). Just use the `remotes::install_github()` function and check out a previous commit from the history, it is documented in examples I think.
2. you can stylize the errors, something that wasn't possible before -- let me check and I see if I can reproduce the old style

**Comment by m-jahn** [comment]
I have looked into the configuration settings for `geom_gene()` and there are indeed not that many ways to customize the appearance of arrows. I have therefore added new commits to the `dev` branch of my fork which fix this problem. They might eventually be merged with the main branch of ggcoverage, in the mean time you can use:

```remotes::install_github("m-jahn/ggcoverage", ref = "dev")```

This will install the newest `ggcoverage` dev branch. With this you have many more options to stylize arrows in the `geom_gene` and `geom_transcript` functions.

This is an example from the vignette:

```{r}
# load metadata
meta_file <-
  system.file("extdata", "RNA-seq", "meta_info.csv", package = "ggcoverage")
sample_meta <- read.csv(meta_file)

# load track
track_folder <- system.file("extdata", "RNA-seq", package = "ggcoverage")
track_df <- LoadTrackFile(
  track.folder = track_folder,
  format = "bw",
  region = "chr14:21,677,306-21,737,601",
  extend = 2000,
  meta.info = sample_meta
)

# coverage plot
basic_coverage <- ggcoverage(
  data = track_df,
  plot.type = "facet",
  range.position = "in",
  facet.y.scale = "fixed"
)

# load gtf file
gtf_file <-
  system.file("extdata", "used_hg19.gtf", package = "ggcoverage")
gtf_gr <- rtracklayer::import.gff(con = gtf_file, format = "gtf")

# plot with default style
basic_coverage +
  geom_gene(gtf.gr = gtf_gr)
```

![image](https://github.com/user-attachments/assets/781e67d7-6456-4191-99ad-297f46da3020)

Now with some additional work, you can get this:

```
# plot with custom style
basic_coverage +
  geom_gene(
    gtf.gr = gtf_gr,
    exon.size = 2.0,
    arrow.size.im = 1.0,
    arrow.length.im = 5,
    arrow.type.im = "open",
    color.by.im = "strand",
    fill.color = c(
      "-" = "darkblue",
      "+" = "darkgreen"
    )
  )
```

![image](https://github.com/user-attachments/assets/5953c3e3-809f-4c91-89ff-f9f95eb89037)

This should be pretty close to the original look of the genes.

**Comment by bvaldebenitom** [comment]
Hi @m-jahn !

Sorry for taking long in answering, and thank you so much for this. It's amazing!

I just tested it, and liked now the definition of intermittent arrows, and the distinction with the arrows in the exons, with both being customizable.

Thanks again for the great work.
