### ISSUE TITLE
unable to plot a basic coverage?

### ISSUE THREAD

**Issue by takahyoro** [showteeth/ggcoverage#4]
I could not plot a basic coverage from my .bw files converted from .bam by deeptools.
I wonder whether I misunderstood what the manual says.

<Error massage>
Error in UseMethod("group_by") : no applicable method for 'group_by' applied to an object of class "NULL" `

The full code run follows: 
library("rtracklayer")
library("graphics")
library("ggcoverage")

bw <- c("~/data1.bam.bw", "~/data2.bam.bw")
meta<- data.frame(SampleName=c("data1.bam", "data2.bam"),
                      Type=c("type1","type2"),
                      Group=c("group1", "group2"))
track.df <- LoadTrackFile(bw,
                         meta.info = meta,
                         format ="bw")
ggcoverage(data = track.df)

---environment---
R version 4.2.2 (2022-10-31) -- "Innocent and Trusting"
Platform: x86_64-apple-darwin17.0 (64-bit)

**Comment by showteeth** [comment]
Hi,   
Can you provide the `track.df` you loaded? And `ggcoverage` have some presented parameters, such as `region = "chr14:21,677,306-21,737,601"`, `gene.name = "HNRNPC"`, this is full help information of [ggcoverage](https://showteeth.github.io/ggcoverage/reference/ggcoverage.html).

**Comment by takahyoro** [comment]
Thank you for your kindness.

The track.df file was attatched.
And I am reading the full help information carefully.

[221122_track_df.txt](https://github.com/showteeth/ggcoverage/files/10063568/221122_track_df.txt)

**Comment by showteeth** [comment]
If you **do not need to add annotation**, you can use the `geom_coverage` which is designed to visualize coverage plot. And [ggcoverage](https://showteeth.github.io/ggcoverage/reference/ggcoverage.html) requires gtf to extract region.

```R
library(ggplot2)
test = read.table('./221122_track_df.txt', header = T)
ggplot() +
  geom_coverage(data = test, color = "auto", mark.region = NULL) +
  theme_coverage()
```

![image](https://user-images.githubusercontent.com/43517166/203240416-b6a254d9-5fa2-4ef2-87c4-f67b7d50f7c9.png)

Let me know if that helps or if you have any other questions.

YB

**Comment by takahyoro** [comment]
Thank you very much for your suggestion.

The script you provided with a little modification worked well, although `color = "auto"` and `theme_coverage()` did not work (I haven't known why).
Anyway, I finally got the plot I intended. Again thank you very much.

**Comment by showteeth** [comment]
Glad to hear that!   
But, what do you mean 
>color = "auto" and theme_coverage() did not work (I haven't known why).   

Can you explain this in detail, such as **the codes you used** and **the results you want**.

**Comment by takahyoro** [comment]
The codes and following results are shown below.

<code#1>
library(ggplot2)
test <- read.table('./221122_track_df.txt', header = T)
ggplot() +
  geom_coverage(data = test,  color = "auto", mark.region = NULL) +
  theme_coverage()
<result#1>
Error in coord_cartesian(xlim = x.range) : 
  argument "x.range" is missing, with no default
In addition: Warning message:
In geom_coverage(data = test, color = "auto", mark.region = NULL) :
  The color you provided is not as long as Type column in data, select automatically!

<code#2>
library(ggplot2)
test <- read.table('./221122_track_df.txt', header = T)
ggplot() +
  geom_coverage(data = test, mark.region = NULL) +
  theme_coverage()
<result#2>
Error in coord_cartesian(xlim = x.range) : 
  argument "x.range" is missing, with no default

**Comment by showteeth** [comment]
I see, **this error occurs when the version of  `ggcoverage`  you used is below 0.8.0**!

You can update `ggcoverage` with following codes:
```R
# install via Github
# install.package("remotes")   #In case you have not installed it.
remotes::install_github("showteeth/ggcoverage")
```

**Comment by SidG13** [comment]
I'm having the same issue, but when I try to install from GitHub I get the error:

```
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called ‘GenomeMatrix’
Calls: <Anonymous> ... loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
Execution halted
ERROR: lazy loading failed for package ‘ggcoverage’
* removing ‘/Library/Frameworks/R.framework/Versions/4.2/Resources/library/ggcoverage’
Warning message:
In i.p(...) :
  installation of package '/var/folders/qf/rdy0lrwd4y33lwzdcrj91hfm0000gn/T//Rtmp2gajfu/fileaf73433d1d08/ggcoverage_1.2.0.tar.gz' had non-zero exit status
```

Looking online, I can't find any package called 'GenomeMatrix'. Will v0.8.0 be available on CRAN at some point?

**Comment by showteeth** [comment]
Hi,

I am sorry for this error!
'GenomeMatrix <https://github.com/areyesq89/GenomeMatrix>' is a package
used for the visualization of TAD (Hi-C data), it can be installed via `
BiocManager::install("areyesq89/GenomeMatrix")`.
I have tested on a new environment to install GenomeMatrix, and it worked:
[image: image.png]
I plan to submit ggcoverage to Bioconductor, and it is under preparation.
By the way, now ggcoverage is v1.2.0.
Please let me know if you have any problems!

YB

Sid Gopalan ***@***.***> 于2023年6月9日周五 02:39写道：
