### ISSUE TITLE
enable range selection for "LoadTrackFile"

### ISSUE THREAD

**Issue by hy09** [showteeth/ggcoverage#5]
Hi, thanks for providing this useful tool. However, I found that the function "LoadTrackFile()" could be very slow and require lots of resources when loading genome-wide signal files. I noticed that the "import()" function from "rtracklayer" was used to import bigwig, wig, and bedgraph files. I was wondering if the "selection" option from "import.bw()" could be added to allow users to load only a portion of the bigwig files (e.g. one chromosome, regions of interest). This could make the function more flexible and much faster.

Thanks!

**Comment by showteeth** [comment]
Hi,

Thanks for your valuable advice, I will improve this in the next release version!

**Comment by showteeth** [comment]
Implemented! [LoadTrackFile](https://github.com/showteeth/ggcoverage/blob/5ed9c654cdabca9e8085019a57ab3c1c3fdfd8b4/R/LoadTrack.R#L48)
