### ISSUE TITLE
Is it possible to set custom y-axis limits?

### ISSUE THREAD

**Issue by ah3918** [showteeth/ggcoverage#6]
Hi, I was wondering whether it was possible to specify the y-axis limits. As you can see from the attached picture, the ranges between the three coverage 5 coverage plots are quite different and may be misleading at first glance.

Loving the package though, thanks for creating it.

![image](https://user-images.githubusercontent.com/59565965/226673392-19dc69e0-7389-40a7-ab11-93cc6c44c60c.png)

**Comment by ah3918** [comment]
To be clear, this is with the `ggcoverage` function!

**Comment by showteeth** [comment]
H,
Before I update, you can use the following codes to do this:
```R
# the example usage
basic.coverage = ggcoverage(data = track.df, color = "auto", 
                            mark.region = NULL, range.position = "out")
# modify y-axis limits
basic.coverage + scale_y_continuous(
  limits = c(0, 1500),
  breaks = 1500,
  expand = c(0, 0)
)
```

Please note that you can modify the figure generated with `ggplot2`. In detail, see this [vignette](https://showteeth.github.io/ggcoverage/articles/CustomizeThePlot.html)

Hope it helps!

YB

**Comment by ah3918** [comment]
Amazing, thank you so much! I wasn't sure you could add ggplot parameters. Thanks!
