### ISSUE TITLE
Load arabidopsis annotation 

### ISSUE THREAD

**Issue by Bartusv** [showteeth/ggcoverage#7]
I am trying to load the Arabidopsis annotation of https://www.arabidopsis.org/download_files/Genes/TAIR10_genome_release/TAIR10_gff3/TAIR10_GFF3_genes_transposons.gff

I have converted the file to GTF with AGAT and changed the feature names "Name" to "gene_name" and "Note" to "gene_type"

Resulting in a file structured like so: 

##gtf-version 3
ChrM	TAIR10	gene	273	734	.	-	.	gene_id "ATMG00010"; ID "ATMG00010"; gene_name "ATMG00010"; gene_type "protein_coding_gene";
ChrM	TAIR10	transcript	273	734	.	-	.	gene_id "ATMG00010"; transcript_name "ATMG00010.1"; ID "ATMG00010.1"; level "1"; gene_name "ATMG00010.1"; Parent "ATMG00010"; original_biotype "mrna";
ChrM	TAIR10	exon	273	734	.	-	.	gene_id "ATMG00010"; transcript_name "ATMG00010.1"; ID "exon-215746"; Parent "ATMG00010.1";
ChrM	TAIR10	CDS	273	734	.	-	0	gene_id "ATMG00010"; transcript_name "ATMG00010.1"; ID "cds-197021"; Parent "ATMG00010.1";
ChrM	TAIR10	gene	273	734	.	-	.	gene_id "nbis-gene-35265"; ID "nbis-gene-35265";
ChrM	TAIR10	transcript	273	734	.	-	.	gene_id "nbis-gene-35265"; transcript_name "ATMG00010.1-Protein"; ID "ATMG00010.1-Protein"; Parent "nbis-gene-35265"; original_biotype "mrna";
ChrM	TAIR10	exon	273	734	.	-	.	gene_id "nbis-gene-35265"; transcript_name "ATMG00010.1-Protein"; ID "nbis-exon-197021"; Parent "ATMG00010.1-Protein";
ChrM	TAIR10	CDS	273	734	.	-	0	gene_id "nbis-gene-35265"; transcript_name "ATMG00010.1-Protein"; ID "cds-197021"; Parent "ATMG00010.1-Protein";
ChrM	TAIR10	gene	8848	11415	.	-	.	gene_id "ATMG00020"; ID "ATMG00020"; gene_name "ATMG00020"; gene_type "rRNA";
ChrM	TAIR10	transcript	8848	11415	.	-	.	gene_id "ATMG00020"; transcript_name "ATMG00020.1"; ID "ATMG00020.1"; level "1"; gene_name "ATMG00020.1"; Parent "ATMG00020"; original_biotype "rrna";
ChrM	TAIR10	exon	8848	11415	.	-	.	gene_id "ATMG00020"; transcript_name "ATMG00020.1"; ID "exon-215747"; Parent "ATMG00020.1";
ChrM	TAIR10	gene	11918	12241	.	+	.	gene_id "ATMG00030"; ID "ATMG00030"; gene_name "ATMG00030"; gene_type "protein_coding_gene";
ChrM	TAIR10	transcript	11918	12241	.	+	.	gene_id "ATMG00030"; transcript_name "ATMG00030.1"; ID "ATMG00030.1"; level "1"; gene_name "ATMG00030.1"; Parent "ATMG00030"; original_biotype "mrna";
ChrM	TAIR10	exon	11918	12241	.	+	.	gene_id "ATMG00030"; transcript_name "ATMG00030.1"; ID "exon-215748"; Parent "ATMG00030.1";
ChrM	TAIR10	CDS	11918	12241	.	+	0	gene_id "ATMG00030"; transcript_name "ATMG00030.1"; ID "cds-197022"; Parent "ATMG00030.1";
ChrM	TAIR10	gene	11918	12241	.	+	.	gene_id "nbis-gene-35266"; ID "nbis-gene-35266";

While plotting I encounter the following error though. 

Error in `geom_segment()`:
! Problem while computing aesthetics.
ℹ Error occurred in the 2nd layer.
Caused by error:
! object 'group' not found
Run `rlang::last_trace()` to see where the error occurred.

Could you please explain me what is going wrong?

**Comment by showteeth** [comment]
Hi,

The error message says **object 'group' not found**, I guess that this may be caused by grouping genes. Would you mind providing the **modified GTF file**, **some test data** and **codes you used**? These will help me find the error.

YB

**Comment by feiyu007** [comment]
I also meet this question. I modified my gtf file. finally, tish error occor. my gtf contents:
![image](https://github.com/showteeth/ggcoverage/assets/17492454/f646d5ed-689a-4902-8b99-90253337d7cd)

**Comment by m-jahn** [comment]
a reproducible example could help, a screenshot is not really

**Comment by m-jahn** [comment]
closed because of missing follow up information.
